# Generated by Django 4.2.7 on 2023-11-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro_TE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('presidente', 'Presidente'), ('vocal_titular', 'Vocal Titular'), ('vocal_suplente', 'Vocal Suplente')], max_length=30)),
                ('fecha_alta', models.DateField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='TribunalEvaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_disposicion', models.IntegerField()),
                ('fecha_disposicion', models.DateField()),
                ('archivo_disposicion', models.FileField(null=True, upload_to='')),
                ('miembros', models.ManyToManyField(to='comision.miembro_te')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_CSTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_asignacion', models.IntegerField(unique=True)),
                ('fecha_alta', models.DateField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.docente')),
            ],
        ),
    ]
