# Generated by Django 4.2.7 on 2023-11-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '__first__'),
        ('comision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunalevaluador',
            name='miembros',
            field=models.ManyToManyField(to='persona.docente'),
        ),
    ]
