# Generated by Django 4.2.7 on 2023-11-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0002_alter_tribunalevaluador_miembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunalevaluador',
            name='miembros',
            field=models.ManyToManyField(to='comision.miembro_te'),
        ),
    ]
