# Generated by Django 4.2.7 on 2023-11-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comision', '__first__'),
        ('persona', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_TF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField()),
                ('titulo_ptf', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivos_adjuntos', models.FileField(null=True, upload_to='')),
                ('certificado_analitico', models.FileField(null=True, upload_to='')),
                ('nota_aceptacion_director', models.FileField(null=True, upload_to='')),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('observaciones', models.CharField(max_length=500, null=True)),
                ('asesor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor_proyecto', to='persona.asesor')),
                ('co_director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codirector_proyecto', to='persona.docente')),
                ('cstf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comision.miembro_cstf')),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_proyecto', to='persona.docente')),
                ('te_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comision.tribunalevaluador')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_TF_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_tf', to='persona.alumno')),
                ('proyecto_tf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='proyectotf.proyecto_tf')),
            ],
        ),
        migrations.CreateModel(
            name='Informe_TF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_itf', models.FileField(null=True, upload_to='archivos_itf/')),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('observaciones', models.CharField(max_length=500, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informe_tf', to='persona.alumno')),
                ('proyecto_tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_tf', to='proyectotf.proyecto_tf')),
            ],
        ),
    ]
