# Generated by Django 4.2.7 on 2023-11-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '__first__'),
        ('proyectotf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_tf',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor_proyecto', to='persona.asesor'),
        ),
        migrations.AlterField(
            model_name='proyecto_tf',
            name='co_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codirector_proyecto', to='persona.docente'),
        ),
        migrations.AlterField(
            model_name='proyecto_tf',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_proyecto', to='persona.docente'),
        ),
    ]
