# Generated by Django 4.2.5 on 2023-11-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alumno_crear_usuario'),
        ('proyectotf', '0002_alter_proyecto_tf_asesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_tf',
            name='proyecto_tf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informe_tf', to='proyectotf.proyecto_tf'),
        ),
        migrations.AlterField(
            model_name='proyecto_tf_alumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_tf', to='persona.alumno'),
        ),
    ]
