# Generated by Django 4.2.5 on 2023-11-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='crear_usuario',
            field=models.BooleanField(default=True),
        ),
    ]
