# Generated by Django 4.2.5 on 2023-11-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alumno_crear_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='crear_usuario',
            field=models.BooleanField(default=True),
        ),
    ]
